//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyFootballApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FantasyFootballApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEN Peyton Manning QB 5 49 368 374
        ///GB Aaron Rodgers QB 10 43 347 316
        ///NO Drew Brees QB 7 39 329 319
        ///DET Matthew Stafford QB 10 25 284 286
        ///CAR Cam Newton QB 13 17 289 315
        ///IND Andrew Luck QB 11 14 282 265
        ///WSH Robert GriffinIII QB 11 15 285 354
        ///PHI Nick Foles QB 8 15 277 333
        ///SEA Russell Wilson QB 5 6 269 370
        ///SF Colin Kaepernick QB 9 10 266 386
        ///ATL Matt Ryan QB 10 2 261 299
        ///NE Tom Brady QB 11 10 261 286
        ///DAL Tony Romo QB 12 7 264 335
        ///SD Philip Rivers QB 11 1 261 359
        ///CHI Jay Cutler QB 10 6 245 292
        ///P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Jamison
        ///-Connor
        ///-Evan
        ///-Kaleb
        ///-Dave
        ///-Andrew
        ///-Gannon
        ///-Eric
        ///-Jordan
        ///
        ///Players.txt
        ///
        ///QB - 25 1
        ///RB - 40 2
        ///WR - 80 3
        ///TE - 15 1
        ///K - 5 1
        ///DST - 5 1
        ///BENCH - 30 7
        ///
        ///150.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newton {
            get {
                object obj = ResourceManager.GetObject("newton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEN Peyton Manning QB 5 49 368 374
        ///GB Aaron Rodgers QB 10 43 347 316
        ///NO Drew Brees QB 7 39 329 319
        ///DET Matthew Stafford QB 10 21 284 286
        ///CAR Cam Newton QB 13 17 289 315
        ///IND Andrew Luck QB 11 14 282 265
        ///WSH Robert GriffinIII QB 11 8 285 354
        ///PHI Nick Foles QB 8 8 277 333
        ///SEA Russell Wilson QB 5 6 269 370
        ///SF Colin Kaepernick QB 9 2 266 386
        ///ATL Matt Ryan QB 10 2 261 299
        ///NE Tom Brady QB 11 2 261 286
        ///DAL Tony Romo QB 12 1 264 335
        ///SD Philip Rivers QB 11 1 261 359
        ///CHI Jay Cutler QB 10 1 245 292
        ///PIT B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stadium {
            get {
                object obj = ResourceManager.GetObject("Stadium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arizona Cardinals ARI 5 389.502628482623 SD +NYG SF +DEN WSH +OAK PHI +DAL STL DET +SEA +ATL KC +STL SEA +SF
        ///Atlanta Falcons ATL 10 299.839019353742 NO +CIN TB +MIN +NYG CHI +BAL DET +TB +CAR CLE ARI +GB PIT +NO +CAR
        ///Baltimore Ravens BAL 12 286.71319505002 CIN PIT +CLE CAR +IND +TB ATL +CIN +PIT TEN +NO SD +MIA JAX +HOU +CLE
        ///Buffalo Bills BUF 10 256.44472953589 +CHI MIA SD +HOU +DET NE MIN +NYJ KC +MIA NYJ CLE +DEN GB +OAK +NE
        ///Carolina Panthers CAR 13 315.011466830084 +TB DET PIT +BAL CHI +CIN +GB SEA N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
    }
}
